include:
  - authentication-microservice/.gitlab-ci.yml
  - example-microservice/.gitlab-ci.yml
  - jobs-microservice/.gitlab-ci.yml
  - scheduler-microservice/.gitlab-ci.yml
  - clusters-microservice/.gitlab-ci.yml
  - commons/.gitlab-ci.yml

